/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ClubRouteImport } from './routes/club'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SpaceRouteImport } from './routes/space'
import { Route as ClubProfileRouteImport } from './routes/club.profile'
import { Route as ClubsIndexRouteImport } from './routes/clubs.index'
import { Route as ClubsClubIdRouteImport } from './routes/clubs.$clubId'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as UserProfileRouteImport } from './routes/user.profile'
import { Route as ClubEventIdRouteImport } from './routes/club.event.$id'
import { Route as ClubEventCreateRouteImport } from './routes/club.event.create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceRoute = SpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubProfileRoute = ClubProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClubRoute,
} as any)
const ClubsIndexRoute = ClubsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClubsRoute,
} as any)
const ClubsClubIdRoute = ClubsClubIdRouteImport.update({
  id: '/$clubId',
  path: '/$clubId',
  getParentRoute: () => ClubsRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubEventIdRoute = ClubEventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => ClubRoute,
} as any)
const ClubEventCreateRoute = ClubEventCreateRouteImport.update({
  id: '/event/create',
  path: '/event/create',
  getParentRoute: () => ClubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/club': typeof ClubRouteWithChildren
  '/clubs': typeof ClubsRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/faculty': typeof FacultyRoute
  '/register': typeof RegisterRoute
  '/space': typeof SpaceRoute
  '/club/profile': typeof ClubProfileRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/events/$id': typeof EventsIdRoute
  '/user/profile': typeof UserProfileRoute
  '/clubs/': typeof ClubsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/club/event/$id': typeof ClubEventIdRoute
  '/club/event/create': typeof ClubEventCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/club': typeof ClubRouteWithChildren
  '/faculty': typeof FacultyRoute
  '/register': typeof RegisterRoute
  '/space': typeof SpaceRoute
  '/club/profile': typeof ClubProfileRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/events/$id': typeof EventsIdRoute
  '/user/profile': typeof UserProfileRoute
  '/clubs': typeof ClubsIndexRoute
  '/events': typeof EventsIndexRoute
  '/club/event/$id': typeof ClubEventIdRoute
  '/club/event/create': typeof ClubEventCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/club': typeof ClubRouteWithChildren
  '/clubs': typeof ClubsRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/faculty': typeof FacultyRoute
  '/register': typeof RegisterRoute
  '/space': typeof SpaceRoute
  '/club/profile': typeof ClubProfileRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/events/$id': typeof EventsIdRoute
  '/user/profile': typeof UserProfileRoute
  '/clubs/': typeof ClubsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/club/event/$id': typeof ClubEventIdRoute
  '/club/event/create': typeof ClubEventCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/club'
    | '/clubs'
    | '/events'
    | '/faculty'
    | '/register'
    | '/space'
    | '/club/profile'
    | '/clubs/$clubId'
    | '/events/$id'
    | '/user/profile'
    | '/clubs/'
    | '/events/'
    | '/club/event/$id'
    | '/club/event/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/club'
    | '/faculty'
    | '/register'
    | '/space'
    | '/club/profile'
    | '/clubs/$clubId'
    | '/events/$id'
    | '/user/profile'
    | '/clubs'
    | '/events'
    | '/club/event/$id'
    | '/club/event/create'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/club'
    | '/clubs'
    | '/events'
    | '/faculty'
    | '/register'
    | '/space'
    | '/club/profile'
    | '/clubs/$clubId'
    | '/events/$id'
    | '/user/profile'
    | '/clubs/'
    | '/events/'
    | '/club/event/$id'
    | '/club/event/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalendarRoute: typeof CalendarRoute
  ClubRoute: typeof ClubRouteWithChildren
  ClubsRoute: typeof ClubsRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  FacultyRoute: typeof FacultyRoute
  RegisterRoute: typeof RegisterRoute
  SpaceRoute: typeof SpaceRoute
  UserProfileRoute: typeof UserProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space': {
      id: '/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof SpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/profile': {
      id: '/club/profile'
      path: '/profile'
      fullPath: '/club/profile'
      preLoaderRoute: typeof ClubProfileRouteImport
      parentRoute: typeof ClubRoute
    }
    '/clubs/': {
      id: '/clubs/'
      path: '/'
      fullPath: '/clubs/'
      preLoaderRoute: typeof ClubsIndexRouteImport
      parentRoute: typeof ClubsRoute
    }
    '/clubs/$clubId': {
      id: '/clubs/$clubId'
      path: '/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof ClubsClubIdRouteImport
      parentRoute: typeof ClubsRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/event/$id': {
      id: '/club/event/$id'
      path: '/event/$id'
      fullPath: '/club/event/$id'
      preLoaderRoute: typeof ClubEventIdRouteImport
      parentRoute: typeof ClubRoute
    }
    '/club/event/create': {
      id: '/club/event/create'
      path: '/event/create'
      fullPath: '/club/event/create'
      preLoaderRoute: typeof ClubEventCreateRouteImport
      parentRoute: typeof ClubRoute
    }
  }
}

interface ClubRouteChildren {
  ClubProfileRoute: typeof ClubProfileRoute
  ClubEventIdRoute: typeof ClubEventIdRoute
  ClubEventCreateRoute: typeof ClubEventCreateRoute
}

const ClubRouteChildren: ClubRouteChildren = {
  ClubProfileRoute: ClubProfileRoute,
  ClubEventIdRoute: ClubEventIdRoute,
  ClubEventCreateRoute: ClubEventCreateRoute,
}

const ClubRouteWithChildren = ClubRoute._addFileChildren(ClubRouteChildren)

interface ClubsRouteChildren {
  ClubsClubIdRoute: typeof ClubsClubIdRoute
  ClubsIndexRoute: typeof ClubsIndexRoute
}

const ClubsRouteChildren: ClubsRouteChildren = {
  ClubsClubIdRoute: ClubsClubIdRoute,
  ClubsIndexRoute: ClubsIndexRoute,
}

const ClubsRouteWithChildren = ClubsRoute._addFileChildren(ClubsRouteChildren)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalendarRoute: CalendarRoute,
  ClubRoute: ClubRouteWithChildren,
  ClubsRoute: ClubsRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  FacultyRoute: FacultyRoute,
  RegisterRoute: RegisterRoute,
  SpaceRoute: SpaceRoute,
  UserProfileRoute: UserProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
